### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by stepanenko3** [llaski/nova-scheduled-jobs#30]
- Conclusion: remove llaski/nova-scheduled-jobs 4.0
    - Conclusion: remove dragonmantank/cron-expression v2.3.0
    - Installation request for llaski/nova-scheduled-jobs ^4.0 -> satisfiable by llaski/nova-scheduled-jobs[4.0].
    - Installation request for laravel/framework ^8.4 -> satisfiable by laravel/framework[v8.4.0].
    - llaski/nova-scheduled-jobs 4.0 requires dragonmantank/cron-expression ^2.2 -> satisfiable by dragonmantank/cron-expression[v2.3.0, v2.2.0].
    - Can only install one of: dragonmantank/cron-expression[v3.0.0, v2.2.0].
    - Can only install one of: dragonmantank/cron-expression[v3.0.0, v2.3.0].
    - laravel/framework v8.4.0 requires dragonmantank/cron-expression ^3.0 -> satisfiable by dragonmantank/cron-expression[3.0.1, v3.0.0].
    - Conclusion: don't install dragonmantank/cron-expression 3.0.1

**Comment by devlsh** [comment]
@llaski Laravel 8 requires cron-expression ^3.0

https://github.com/llaski/nova-scheduled-jobs/blob/master/composer.json#L20

**Comment by llaski** [comment]
Should be fixed now
