### ISSUE TITLE
Be translatable

### ISSUE THREAD

**Issue by amidesfahani** [llaski/nova-scheduled-jobs#34]
hi can you make all fields translatable?

"Command/Job | Description | Schedule | Expression | Next Run At | Without Overlapping | On One Server | Run In Maintenance Mode | Dispatch"

--

and make it optional to change the card width

**Comment by llaski** [comment]
These are all now translatable as of version 6.0.0.

https://github.com/llaski/nova-scheduled-jobs/pull/45
