### ISSUE TITLE
Unable to determine command name from signature

### ISSUE THREAD

**Issue by Olayiwola72** [llaski/nova-scheduled-jobs#35]
Please see error screen shot below.

![image](https://user-images.githubusercontent.com/40915435/129085808-298567ec-4ad8-4648-8ece-6de9cb5007e9.png)

![image](https://user-images.githubusercontent.com/40915435/129085908-5d253d23-18dd-4d7f-9180-d98d2d8f9607.png)

composer.json

![image](https://user-images.githubusercontent.com/40915435/129086002-ced7f8a9-4bca-47d6-bdee-07c3d5d8bf26.png)

**Comment by bilogic** [comment]
same issue

**Comment by Olayiwola72** [comment]
I noticed a new development with this issue. I am not sure what I did, but I think I ran "composer update" and "php artisan clear-compiled commands".

Suddenly the error changed and now its working but error still shows up on the logs

![image](https://user-images.githubusercontent.com/40915435/131087398-0b3cd7e6-34d2-4a77-b049-1578b60eb2db.png)

![image](https://user-images.githubusercontent.com/40915435/131087496-0c9d679c-a444-447a-b010-9ed9169f2e18.png)
