### ISSUE TITLE
Jobs defined in AppServiceProvider are not shown

### ISSUE THREAD

**Issue by gms8994** [llaski/nova-scheduled-jobs#4]
I'm building a system where the users can define schedules for jobs to be run, and as such, I have code written in the AppServiceProvider::register that looks like (extremely simplified example, of course):

```
public function register()
{
    $this->app->booted(function () {
            $schedule = $this->app->make(Schedule::class);

            $schedule->command('this-is-a-test')
            ->description('test-description')
            ->cron('* * * * *');
    });
}
```

This job does not show up in the Nova card, but does show up under hmazter/laravel-schedule-list `php artisan schedule:list`.

**Comment by llaski** [comment]
The package assumes all scheduled jobs live in the `schedule` method of the `app/Console/Kernel.php` file per the usual Laravel setup. Can I ask why you're adding commands in the app service provider as opposed to the `Kernel` file?

**Comment by llaski** [comment]
@gms8994 Please let me know if you were able to find a solution, otherwise will plan on closing out this issue. Thanks!
