### ISSUE TITLE
Laravel 9 and Nova 3 Not Loading

### ISSUE THREAD

**Issue by jamespavett** [llaski/nova-scheduled-jobs#42]
Hello,

I seem to have an issue when running Nova 3 and Laravel 9. Due to version 5 of this package requiring Nova 4, I am still on version 4.

![image](https://user-images.githubusercontent.com/10764464/169803406-4d1b7dc8-3896-4e3f-94f6-9565a35b6150.png)

Both schedule jobs card / tabs just show a loading icon that never resolves with any data.

Looking at the response, the server is getting a 502 error:

![image](https://user-images.githubusercontent.com/10764464/169803552-58b68323-34e1-4942-813c-001ce4f8f248.png)

Not sure if there's any guidance or support you can offer. As I only have a problem with this package, no others.

**Comment by silentpatrik** [comment]
I had same issue, for me it was a server warning when loading that view.
```
 PHP Warning: Private methods cannot be final as they are never overridden by other classes in ...
```
Search an replace in the package directory in vendors folder, for "final private" to "private" temporarily solved it for me.

**Comment by stepanenko3** [comment]
Hi,

try https://github.com/stepanenko3/nova-cards

**Comment by silentpatrik** [comment]
> Hi,
> 
> try https://github.com/stepanenko3/nova-cards

same issue as here since same underlying code is used. I have created a pr for that in other repo.

**Comment by llaski** [comment]
@jamespavett   There is either an issue with one of your scheduled jobs or this package may not support how one of them is configured for version 5. Can you share your configured scheduled jobs code, or share the error your seeing in the console and logs?

**Comment by llaski** [comment]
Closing out as have had no response for 3 months. Feel free to reopen if needed.
