### ISSUE TITLE
[BUG]: Javascript error when pressing the "dispatch" button

### ISSUE THREAD

**Issue by salomonsanz** [llaski/nova-scheduled-jobs#43]
### Description of the bug

I'm using laravel 9.38 and nova 4, when i press the play button to manually dispatch the task, nothing happens.
The console shows this error:

_TypeError: Cannot read properties of undefined (reading 'focus')_

```
 mounted: function() {
    this.$refs.confirmButton.focus()
}
```

### Steps To Reproduce

Click on the "play" button to manually dispatch the scheduled task

**Comment by llaski** [comment]
@salomonsanz Please upgrade to version 6.0.0 and see if this issue persists.

**Comment by llaski** [comment]
Closing out as have had no response for 3 months. Feel free to reopen if needed.
