### ISSUE TITLE
How should I change the card's English into another language?

### ISSUE THREAD

**Issue by phoenixg** [llaski/nova-scheduled-jobs#5]

**Comment by llaski** [comment]
@phoenixg I can look at adding support for additional languages, but I do not currently have time to work on it. Which language were you looking for support for? Also feel free to submit a PR!

**Comment by phoenixg** [comment]
Where should I put language file, I want to add Chinese language

**Comment by llaski** [comment]
@phoenixg You can put it in the resources folder and follow the Laravel convention (so resources/lang/zh/ and then the translation files would go there.

**Comment by phoenixg** [comment]
@llaski I don't find language files under your package, so I can't figure out the convention.

**Comment by llaski** [comment]
@phoenixg As previously mentioned I don't currently have time to add language support for this package, so if you wanted to add it would need to be done from scratch for English and your language of choice, and then the code would need to be edited to use the translation files.

**Comment by klimov-paul** [comment]
PR: #16
