### ISSUE TITLE
How should I move the default "Scheduled Jobs" navigation bar into another resource?

### ISSUE THREAD

**Issue by phoenixg** [llaski/nova-scheduled-jobs#6]
I'm using [nova-categories-resources](https://novapackages.com/packages/alexbowers/nova-categorise-resources) to manage my category, how to make `Scheduled Jobs` under my own resource category?

**Comment by llaski** [comment]
@phoenixg This package comes with a tool and a card, neither of which are resources. You could add the card to an existing resource to have it appear there, but the main tool is it's own page and is not compatible with a resource to my knowledge at this time.
