### ISSUE TITLE
Scheduled Job as a callback function do not display

### ISSUE THREAD

**Issue by jonnywilliamson** [llaski/nova-scheduled-jobs#7]
Hi, I love this nova card but I seem to have an issue with one type of job in my scheduler.

```php
        $schedule
            ->call(function () {

                Mail::to('test@example.com')
                    ->sendNow(new DemoEmail());

            })
            ->timezone('Europe/Dublin')
            ->dailyAt('12:00'));
```

Any time this type of code is in the `kernel.php` file, the entire page fails to load.

![image](https://user-images.githubusercontent.com/2513663/48943166-3f994e80-ef1a-11e8-9eb7-16b3df36070f.png)

Any ideas what I can do/how to fix this?

**Comment by jonnywilliamson** [comment]
Discovered this in the browser console as the page is trying to load:

![image](https://user-images.githubusercontent.com/2513663/48962115-7baccd80-ef73-11e8-9667-1cc891a7b621.png)

![image](https://user-images.githubusercontent.com/2513663/48962131-de05ce00-ef73-11e8-98f7-19c852e8901d.png)

**Comment by llaski** [comment]
@jonnywilliamson This package doesn't support jobs within a callback right now. I can look into this next week, or your welcome to open a PR. You would want to look into the `src/Schedule` folder at the CommandEvent and JobEvent for what is currently supported and then figure out what is available for a callback. Would imagine there isn't much info available to display for it on the frontend unfortunately so would highly recommend using jobs or commands for all of your scheduling.

**Comment by jonnywilliamson** [comment]
Made a simple PR to work around this. Working fine now here. Not sure if its the way you wish to approach it.
